// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcpsturmkxsvlpfyqxnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjcHN0dXJta3hzdmxwZnlxeG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTE4OTgsImV4cCI6MjA2NzYyNzg5OH0.8d_LIUhOnxENM74PcrEnP9tmVWTb9KKXEqXR_uVI0sM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});